version: "3.9"
services:
  mongo:
    image: mongo:6.0.5
    ports:
    - 27018:27017
    volumes:
    - ./post-service-data:/data/db
  nginx:
    image: nginx:1.24.0
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - NODE_DEBUG=http