version: "3.9"
services:
  mongo:
    image: mongo
    ports:
    - 27018:27017
    volumes:
    - ./post-service-data:/data/db
  web:
    build: .
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    ports:
    - "3000:3000"