version: "3.9"
services:
  mongo:
    image: mongo
    ports:
    - 27018:27017
    volumes:
    - ./post-service-data:/data/db
  web:
    build: .
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
    - "3000:3000"
volumes:
  data-volume: