version: "2"
services:
  mongo:
    image: mongo
    ports:
    - "27018:27017"
    volumes:
    - ./post-service-data:/data/db
  web:
    build: .
    environment:
      - DB_HOST=mongo
    ports:
    - "3000:3000"
volumes:
  data-volume: